/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChargesForm.java
 *
 * Created on Jun 14, 2012, 11:41:43 PM
 */
package iibiznes.frame;

import iibiznes.fields.BoardInfo;
import iibiznes.fields.FieldInfo;
import java.awt.Color;

/**
 *
 * @author grzes
 */
public class ChargesForm extends javax.swing.JPanel
{

    /** Creates new form ChargesForm */
    public ChargesForm()
    {
        initComponents();
        setEditorPane();
        fillCombo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboTopics = new javax.swing.JComboBox();
        lblTopic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JEditorPane();

        comboTopics.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTopicsItemStateChanged(evt);
            }
        });

        lblTopic.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lblTopic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopic.setText("Topic");

        jScrollPane1.setViewportView(editor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(comboTopics, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(comboTopics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboTopicsItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboTopicsItemStateChanged
    {//GEN-HEADEREND:event_comboTopicsItemStateChanged
        choice();
    }//GEN-LAST:event_comboTopicsItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboTopics;
    private javax.swing.JEditorPane editor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTopic;
    // End of variables declaration//GEN-END:variables

    private void fillCombo()
    {
        FieldInfo[] fi = BoardInfo.getFields();
        for (FieldInfo f: fi)
            if (   f.type.equalsIgnoreCase("topic")
                || f.type.equalsIgnoreCase("other") )
            {
                comboTopics.addItem(f.name);
            }
    }

    private void setEditorPane()
    {
        editor.setContentType("text/plain");
        editor.setEditable(false);
    }
    
    private void choice()
    {
        String topic = comboTopics.getSelectedItem().toString();
        FieldInfo[] fields = BoardInfo.getFields();
        FieldInfo fi = null;
        for (int i = 0; i < fields.length; ++i)
        {
            if (fields[i].name.equalsIgnoreCase(topic))
            {
                fi = fields[i];
                break;
            }
        }
        if (fi == null)
        {
            System.err.println("No such topic \"" + topic + "\".");
        }
        setContent(fi);
    }
    
    private void setContent(FieldInfo fi)
    {
        if (fi == null)
        {
            editor.setText("");
            lblTopic.setText("");    
            return ;
        }
        editor.setText(fi.chargeDesc());
        lblTopic.setText(fi.name);
        if (fi.type.equalsIgnoreCase("topic"))
            lblTopic.setForeground(BoardInfo.topicToSubject(fi.name).color);
        else lblTopic.setForeground(Color.DARK_GRAY);
    }
    
}
